#!/bin/bash
# Get the directory of the currently executing script
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Update files on the ESP32
source "$script_dir/update_files"

# Specify file to upload
# main_file="main.py"
main_file="main.py"

# Upload file as main.py
ampy --port COM6 put "$main_file" main.py